# Generated by Django 5.2 on 2025-05-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HiveMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('QB', 'Queen Bee'), ('BK', 'Buzzkeeper'), ('WORKER_BEE', 'Worker Bee')], default='WORKER_BEE', max_length=50)),
                ('joined_on', models.DateTimeField()),
            ],
        ),
    ]
