# Generated by Django 5.2 on 2025-05-02 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hivemembership',
            name='hive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hive_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hivemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
