# Generated by Django 5.2 on 2025-05-03 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivemembership',
            name='hive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hive_membership', to='hive.hive'),
        ),
    ]
