# Generated by Django 5.2 on 2025-05-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hive", "0003_alter_hivemembership_hive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hivemembership",
            name="joined_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
