# Generated by Django 5.2 on 2025-05-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TD', 'To Do'), ('IP', 'In Progress'), ('D', 'Done'), ('OD', 'Overdue')], default='TD', max_length=50),
        ),
    ]
